### ISSUE TITLE
Content Issue In Image

### ISSUE THREAD

**Issue by PatwalRohit** [MicrosoftDocs/CordovaDocs#36]
There is a content spelling issue in the image: Test Script run by suitable "ranguage" runtime.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8db1c71-2ade-27cb-9e60-61d6f1c86ac2
* Version Independent ID: e151c18c-b900-0676-a6e2-b06ae9b7a301
* Content: [UI Testing for Apache Cordova Apps with Appium - Cordova](https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/debug-test/ui-testing-with-appium?view=toolsforcordova-2017)
* Content Source: [cordovadocs/2017/debug-test/ui-testing-with-appium.md](https://github.com/MicrosoftDocs/CordovaDocs/blob/live/cordovadocs/2017/debug-test/ui-testing-with-appium.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for reporting this! For some reason I'd fixed it in the source image but never got the change propagated to the live docs.

**Comment by kraigb** [comment]
#conceptdev Please merge the PR and close the issue at your convenience.

**Comment by conceptdev** [comment]
Updated image merged - thanks :)
