### ISSUE TITLE
404 Links

### ISSUE THREAD

**Issue by ffigu002** [MicrosoftDocs/CordovaDocs#68]
Links to "Build Apache Cordova Apps" and "Learn about other CI options" lead to 404 not found pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bce1fe14-cfee-728b-e209-6846e3604968
* Version Independent ID: 48c98a30-04de-3629-1306-08fbeec380dc
* Content: [Use Apache Cordova with Visual Studio Team Services - Cordova](https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/build-deploy/visual-studio-team-services?view=toolsforcordova-2017#feedback)
* Content Source: [cordovadocs/2017/build-deploy/visual-studio-team-services.md](https://github.com/MicrosoftDocs/CordovaDocs/blob/live/cordovadocs/2017/build-deploy/visual-studio-team-services.md)
* Product: **visual-studio-dev15**
* Technology: **cordova**
* GitHub Login: @johnwargo
* Microsoft Alias: **jowargo**

**Comment by johnwargo** [comment]
@ffigu002 I submitted an edit to remove the one link, but the CI link works fine for me.  I'm no longer on the Cordova Docs team, so we'll see if someone will process this request.

Remember, the docs are open source, so if you find an error, submit a PR to fix it.

**Comment by ffigu002** [comment]
@johnwargo  Yes you are correct, the CI link works for me as well, is the last link that is giving the 404. Unfortunately there are more Cordova Docs that are missing, such as the "usage and tutorial" links when navigating to the marketplace extension https://marketplace.visualstudio.com/items?itemName=ms-vsclient.cordova-extension

Hopefully someone from the team can update them as I have been looking for help/reference on how to use the extension, thanks for the help!

**Comment by johnwargo** [comment]
@ffigu002 I doubt it, these docs haven't been updated in a long time; I worked on them as a contractor three years ago (during development of Visual Studio 2017 and TACO).  The only tooling from Microsoft now for Cordova developers is [here](https://marketplace.visualstudio.com/items?itemName=msjsdiag.cordova-tools); that tool is in active development, the TACO stuff is not.

**Comment by ffigu002** [comment]
@johnwargo  Okay that helps a lot, I'm going to move on to the new tooling. I'll go ahead and close it out. Thanks for the help!
